name: 📦 Request Paket Baru
description: Ajukan paket baru agar ditambahkan ke KYRT CDN
title: "[REQUEST] "
labels: ["package request"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Terima kasih sudah ingin berkontribusi pada **KYRT CDN**!  
        Isi form di bawah untuk mengajukan paket baru agar bisa ditambahkan ke sistem CDN kami.

  - type: input
    id: nama-paket
    attributes:
      label: Nama Paket
      description: Nama resmi paket yang ingin kamu ajukan.
      placeholder: Contoh: bootstrap, tailwindcss, jquery
    validations:
      required: true

  - type: input
    id: versi-paket
    attributes:
      label: Versi Paket
      description: Versi tertentu yang ingin ditambahkan (opsional, biarkan kosong untuk versi terbaru).
      placeholder: Contoh: 5.3.2

  - type: input
    id: sumber
    attributes:
      label: Sumber / URL Resmi
      description: Link ke npm, GitHub, jsDelivr, atau repo resmi paket tersebut.
      placeholder: Contoh: https://www.npmjs.com/package/bootstrap
    validations:
      required: true

  - type: textarea
    id: alasan
    attributes:
      label: Alasan Permintaan
      description: Jelaskan kenapa paket ini perlu ditambahkan ke KYRT CDN.
      placeholder: |
        Contoh:
        - Banyak digunakan oleh komunitas
        - Diperlukan untuk proyek web modern
        - Tidak tersedia di CDN lain
    validations:
      required: true

  - type: checkboxes
    id: konfirmasi
    attributes:
      label: Konfirmasi
      options:
        - label: Saya sudah mencari paket ini di KYRT CDN dan belum tersedia
          required: true
        - label: Saya yakin paket ini aman dan legal untuk dibagikan secara publik
          required: true
