name: "📦 Packages Request"
description: "Buat Paket NPM Kamu Agar Masuk ke KYRT CDN"
labels:
  - "📦 Packages Request"

body:
  - type: markdown
    attributes:
      value: |
        ## Request Paket Anda ke KYRT CDN

        Terima Kasih Anda Sudah Datang ke KYRT CDN!  
        Ada dua cara untuk mengajukan paket:
        1. **Isi URL ke file konfigurasi JSON** (`kyrt-cdn-package.json`) yang sudah tersedia di internet (raw URL).  
           - Jika URL valid dan file JSON valid, maka **Anda boleh melewati** pengisian form di bawah.
        2. **Atau isi form** di bawah ini secara lengkap jika Anda tidak menyediakan JSON config.

        **Catatan:** GitHub Issue Forms saat ini belum mendukung conditional show/hide fields secara native.  
        Untuk itu kami memakai aturan sederhana: *Jika Anda memberikan JSON Config URL yang valid, form bisa dilewati; jika tidak, mohon isi semua field di form.*

  - type: input
    id: json_config_url
    attributes:
      label: URL JSON Config (opsional)
      description: "Masukkan raw URL yang mengarah ke file `kyrt-cdn-package.json` (contoh: https://raw.githubusercontent.com/username/repo/main/kyrt-cdn-package.json). Jika diisi dan valid, Anda boleh melewatkan pengisian form di bawah."
      placeholder: "https://raw.githubusercontent.com/username/repo/main/kyrt-cdn-package.json"
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---  
        **Jika Anda TIDAK mengisi field di atas (JSON Config URL), mohon lengkapi form di bawah.**

  - type: input
    id: package_name
    attributes:
      label: Nama Paket
      description: "Masukkan nama paket Anda."
      placeholder: "Contoh: jquery"
    validations:
      required: true

  - type: input
    id: package_version
    attributes:
      label: Versi Paket
      description: "Versi paket Anda."
      placeholder: "Contoh: 1.0.0"
    validations:
      required: true

  - type: input
    id: npm_link
    attributes:
      label: Link NPM Paket
      description: "Masukkan link resmi paket Anda dari NPM."
      placeholder: "https://www.npmjs.com/package/example"
    validations:
      required: true

  - type: input
    id: repository_link
    attributes:
      label: Link Repository / Homepage
      description: "Opsional. Link GitHub atau website paket."
      placeholder: "https://github.com/username/repo"
    validations:
      required: false

  - type: input
    id: download_count
    attributes:
      label: Jumlah Download NPM
      description: "Masukkan total download (minimal 2.000)."
      placeholder: "Contoh: 2500"
    validations:
      required: true

  - type: input
    id: include_files
    attributes:
      label: File yang Ingin Di-include ke CDN
      description: "Masukkan file, pisahkan dengan koma."
      placeholder: "dist/main.js, dist/style.css, LICENSE"
    validations:
      required: true

  - type: dropdown
    id: is_static
    attributes:
      label: Apakah Paket Anda Statis?
      description: "Pilih YA jika paket statis (wajib)."
      options:
        - "YA, paket saya statis"
        - "TIDAK, paket saya dinamis"
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: Kenapa Paket Anda Cocok Masuk KYRT CDN?
      placeholder: "Contoh: Paket saya populer dan digunakan oleh banyak developer."
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Catatan Tambahan
      placeholder: "Contoh: Tidak ada."
    validations:
      required: false

  - type: checkboxes
    id: agree
    attributes:
      label: Persetujuan
      options:
        - label: "Saya menyetujui semua syarat KYRT CDN."
    validations:
      required: true
